bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: pQjWFXWz+l9JCz6ypTrGVz09TnqxI/qFmaym6e0wSm/38Yq7KkBfyMHt5Ry6BgsLIoqqs36SrKv7EHjhMauEQwwdvdlRW1IfdtIXllGcuCZL+eOcoJIly9VlyidKoYlrrbMT7VQVpmPHUf56EtmcxlIY3diBCAMnvEK0NCiNNK4wAqfmkpw32EeXwBHmJVr6ocJhWexOOsiMg0voTZc930DFX6pcHVA+a5xx3opb1UrAjhr5YJlYMF9NpG+Iz+XK8Md5BRFIngr0i2eY5AJ0rrirR+v6cJJHOkDEs0Ij4dk2w9pHTmlRm/7NaD0rEGpV2+QwPzJCJj9lWHjcjcdbcFkR4G4udUlG/rwieoC55gDVoO/OZCeI4GIgTCcS/M644Amr+DQjaYADhOtIfbYMQV5EoxUcTx5D7X/mhHiQ0KWNLmZMZyM+D1P59dAJoTYucf0Oq2pH/JiqH/WRzNvpAA3tNLdKCqTq++TFOG7hJSNx9UIfTcLq4mClhBejUekJHuHnHdewSR9ZXdU+5YXgiZm23KgmcX/QA0qYsBy5wZEF1asUDZQFy3yDKOHaF0gN6DrGxgEcCCU3AMeP5Vq7YMIPGIZCet5mlac5ya0Y8REQInI6dyW4EBPOsDABWHsaV+jVs40PHo3dXhaNWSOLV1C57OjkKbgi36HQ2d+6p7g=
conda_forge_output_validation: true
